x-workflow: &workflow
  image: pcr-assay-design-workflow:latest
  platform: linux/amd64
  working_dir: /app
  stdin_open: true
  tty: true
  volumes:
    - .:/app

services:
  design:
    <<: *workflow
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - conda
      - run
      - --no-capture-output
      - -n
      - pcr-assay-design-workflow
      - python3
      - 01_varvamp_assay_design.py
    command: []

  validation:
    <<: *workflow
    entrypoint:
      - conda
      - run
      - --no-capture-output
      - -n
      - pcr-assay-design-workflow
      - python3
      - 02_in_silico_validation.py
    command: []
