name: pcr-assay-design-workflow

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11

  # ============================================================
  # Workflow 01 - Assay design
  # ============================================================

  # Sequence orientation and multiple sequence alignment
  - mafft=7.505

  # Redundancy reduction
  - cd-hit=4.8.1
  - seqkit

  # Alignment trimming
  - trimal

  # Python libraries
  - biopython
  - pandas
  - matplotlib
  - pillow
  - pymupdf

  # ============================================================
  # Workflow 02 - In silico validation
  # ============================================================

  # Probe validation with BLAST+
  - blast

  # ============================================================
  # VarVAMP
  # ============================================================

  - pip
  - pip:
      - varvamp==1.3.2